/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [order_id]
      ,[order_date]
      ,[status]
      ,[item_id]
      ,[sku]
      ,[qty_ordered]
      ,[price]
      ,[value]
      ,[discount_amount]
      ,[Discount_Percent]
      ,[Selling price]
      ,[category]
      ,[payment_method]
      ,[year]
      ,[month]
      ,[Gender]
      ,[age]
      ,[City]
      ,[Reasons for cancelation and order refund]
  FROM [Carrefour Sales].[dbo].[Carrefour$]
  WHERE [status] like 'r%';

  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [ProductID]
      ,[Weight]
      ,[FatContent]
      ,[ProductVisibility]
      ,[ProductType]
      ,[MRP]
      ,[Sales]
      ,[Budgeted Sales]
      ,[OutletID]
      ,[Date]
      ,[OutletSize]
      ,[LocationType]
      ,[OutletType]
  FROM [Big Mart Sales].[dbo].['Big Mart Sales$']
  WHERE [ProductType] like 'D%';